backend:
  name: git-gateway
  branch: main
media_folder: "public/uploads"
publish_mode: editorial_workflow
collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
